Output adios.mp4
Require claude

Set Width 1200
Set Height 1200
Hide
Set Shell bash
Sleep 500ms
Type "claude --dangerously-skip-permissions"
Enter
Sleep 2s
Type "/clear"
Enter
Show
Sleep 2s
Type "What can you tell me about the simulation based on the dataset."
Enter
Sleep 30s
Type "What was the initial temperature of the system?"
Enter
Sleep 15s
Type "How many gold atoms are in the simulation?"
Enter
Sleep 15s
Type "What are the dimensions of the simulation box?"
Enter
Sleep 15s
Type "What is the total duration of the simulation in picoseconds?"
Enter
Sleep 15s
Type "What is the crystal structure of the gold at the beginning of the simulation?"
Enter
Sleep 15s
Type "Plot the positions of the atoms at the final timestep?"
Enter
Sleep 360s
Type "Plot the trajectory of a single atom over time. The atom of choice should a parameter to the script. The output of the script should a PNG image with the results. Run the script for any single atom"
Enter
Sleep 360s
Type "/exit"
Enter