Output adios.mp4
Require claude

Set Width 1200
Set Height 1200

Set Shell zsh
Sleep 500ms
Type "claude --dangerously-skip-permissions"
Enter
Sleep 2s
Type "/clear"
Enter
Sleep 2s
Type "What can you tell me about the simulation based on the dataset."
Enter
Sleep 60s
Type "What was the initial temperature of the system?"
Enter
Sleep 30s
Type "How many gold atoms are in the simulation?"
Enter
Sleep 30s
Type "/exit"
Enter
